 // File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkNCyFYRsWZR__3nhXkh2_h772ZVzt5o8',
    appId: '1:742289045647:web:2a0dd4bd854d03834bd8fa',
    messagingSenderId: '742289045647',
    projectId: 'flutter-app-distribution-44807',
    authDomain: 'flutter-app-distribution-44807.firebaseapp.com',
    storageBucket: 'flutter-app-distribution-44807.appspot.com',
    measurementId: 'G-JEVHS69L35',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlNgAo9rRAoCKZhbk0olpli05cv3UFJRs',
    appId: '1:742289045647:android:7eb2328264af5fa64bd8fa',
    messagingSenderId: '742289045647',
    projectId: 'flutter-app-distribution-44807',
    storageBucket: 'flutter-app-distribution-44807.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_-DDs8FaCxg7CmUoOLSSlbitts7IXjTY',
    appId: '1:742289045647:ios:ed6680782b89bf4d4bd8fa',
    messagingSenderId: '742289045647',
    projectId: 'flutter-app-distribution-44807',
    storageBucket: 'flutter-app-distribution-44807.appspot.com',
    iosBundleId: 'com.example.bookingAppointment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkNCyFYRsWZR__3nhXkh2_h772ZVzt5o8',
    appId: '1:742289045647:web:17581b17fbb5f5e84bd8fa',
    messagingSenderId: '742289045647',
    projectId: 'flutter-app-distribution-44807',
    authDomain: 'flutter-app-distribution-44807.firebaseapp.com',
    storageBucket: 'flutter-app-distribution-44807.appspot.com',
    measurementId: 'G-8Y574NT0B2',
  );
}
